### DISCUSSION TITLE
Android - "libc++abi: terminating" crash

### DISCUSSION THREAD

**Discussion by orhangulcan** [google/filament#5956] [General]
After loading a model to the android filament model viewer, I encounter this error when I want to load another model again. Or I get this error when I navigate to another page from the viewer page (with navigation component) and then when I come back to the viewer page and want to load the model again. Anyone encountered this before?

Logs: 

```
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
```
```
E/libc++abi: terminating
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29967
```

**Comment by pixelflinger** [comment]
It would be nice to have more info about this crash.  Sample code, model you are using. And are you using the camera? (looks like you are).

There is not much we can do here with the given information.

**Comment by romainguy** [comment]
The whole crash log would be useful too. It looks like an app issue since a `Stream` is involved, which I don't believe `ModelViewer` ever uses on its own.

**Comment by orhangulcan** [comment]
Hİ, thanks for the answers,
I am using the camera, but I am using the camera on the page I go from model-viewer. I don't use the camera on the page with Model-Viewer.

My full logs are here :
```
E/Filament: in setImage:210
    reason: The combination of internal format=0 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in setImage:210
    reason: The combination of internal format=0 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in setImage:210
    reason: The combination of internal format=0 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:210
    reason: The combination of internal format=49 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in generateMipmaps:408
    reason: Texture format 49 is not mipmappable.
E/Filament: 
E/Filament: in setImage:210
    reason: The combination of internal format=50 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in generateMipmaps:408
    reason: Texture format 50 is not mipmappable.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:210
    reason: The combination of internal format=0 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in setImage:210
    reason: The combination of internal format=0 and {format=6, type=0} is not supported.
E/Filament: 
 E/Filament: in setImage:210
    reason: The combination of internal format=0 and {format=6, type=0} is not supported.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in generateMipmaps:408
    reason: Texture format 58840 is not mipmappable.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in generateMipmaps:408
    reason: Texture format 25966 is not mipmappable.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/Filament: in setImage:214
    reason: setImage() called on a Stream texture.
E/Filament: 
E/libc++abi: terminating
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 30902 (pfab.metaavatar), pid 30902 (pfab.metaavatar)
```
